//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuncionario
    {
        public int nldFuncionario { get; set; }
        public string sNome { get; set; }
        public System.DateTime sNascimento { get; set; }
        public string sCPF { get; set; }
        public string sCargo { get; set; }
        public int nldSetor { get; set; }
        public string sSalario { get; set; }
    
        public virtual tblSetor tblSetor { get; set; }
    }
}
