//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetor
    {
        public tblSetor()
        {
            this.tblFuncionario = new HashSet<tblFuncionario>();
        }
    
        public int nldSetor { get; set; }
        public string sSetor { get; set; }
    
        public virtual ICollection<tblFuncionario> tblFuncionario { get; set; }
    }
}
